# Generated by Django 5.0.14 on 2026-05-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="issues/%Y/%m/%d/")),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pothole", "Яма на дороге"),
                            ("garbage", "Мусор/Свалка"),
                            ("lighting", "Освещение"),
                            ("other", "Другое"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Отправлено"),
                            ("in_progress", "В работе"),
                            ("resolved", "Решено"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
